
{if not tagged "tex_set"
	{if rand 0.50 {delay 0.1 {tex_mod "texset2_var1"}}
	}

	{if rand 0.333 {delay 0.1 {tex_mod "texset3_var1"}}
	else rand 0.5 {delay 0.1 {tex_mod "texset3_var2"}}
	}

	{if rand 0.25 {delay 0.3 {tex_mod "texset4_var1"}}
	else rand 0.333 {delay 0.3 {tex_mod "texset4_var2"}}
	else rand 0.5 {delay 0.3 {tex_mod "texset4_var3"}}
	}

	{if rand 0.20 {delay 0.3 {tex_mod "texset5_var1"}}
	else rand 0.25 {delay 0.3 {tex_mod "texset5_var2"}}
	else rand 0.333 {delay 0.3 {tex_mod "texset5_var3"}}
	else rand 0.5 {delay 0.3 {tex_mod "texset5_var4"}}
	}

	{if rand 0.167 {delay 0.01 {tex_mod "texset6_var1"}}
	else rand 0.20 {delay 0.01 {tex_mod "texset6_var2"}}
	else rand 0.25 {delay 0.01 {tex_mod "texset6_var3"}}
	else rand 0.333 {delay 0.01 {tex_mod "texset6_var4"}}
	else rand 0.50 {delay 0.01 {tex_mod "texset6_var5"}}
	}

	{if rand 0.143 {delay 0.1 {tex_mod "texset7_var1"}}
	else rand 0.167 {delay 0.1 {tex_mod "texset7_var2"}}
	else rand 0.20 {delay 0.1 {tex_mod "texset7_var3"}}
	else rand 0.25 {delay 0.1 {tex_mod "texset7_var4"}}
	else rand 0.333 {delay 0.1 {tex_mod "texset7_var5"}}
	else rand 0.50 {delay 0.1 {tex_mod "texset7_var6"}}
	}

	{if rand 0.125 {delay 0.1 {tex_mod "texset8_var1"}}
	else rand 0.143 {delay 0.1 {tex_mod "texset8_var2"}}
	else rand 0.167 {delay 0.1 {tex_mod "texset8_var3"}}
	else rand 0.20 {delay 0.1 {tex_mod "texset8_var4"}}
	else rand 0.25 {delay 0.1 {tex_mod "texset8_var5"}}
	else rand 0.333 {delay 0.1 {tex_mod "texset8_var6"}}
	else rand 0.5 {delay 0.1 {tex_mod "texset8_var7"}}
	}

	{if rand 0.11 {delay 0.1 {tex_mod "texset9_var1"}}
	else rand 0.125 {delay 0.1 {tex_mod "texset9_var2"}}
	else rand 0.143 {delay 0.1 {tex_mod "texset9_var3"}}
	else rand 0.167 {delay 0.1 {tex_mod "texset9_var4"}}
	else rand 0.20 {delay 0.1 {tex_mod "texset9_var5"}}
	else rand 0.25 {delay 0.1 {tex_mod "texset9_var6"}}
	else rand 0.333 {delay 0.1 {tex_mod "texset9_var7"}}
	else rand 0.5 {delay 0.1 {tex_mod "texset9_var8"}}
	}

	{if rand 0.1 {delay 0.1 {tex_mod "texset10_var1"}}
	else rand 0.11 {delay 0.1 {tex_mod "texset10_var2"}}
	else rand 0.125 {delay 0.1 {tex_mod "texset10_var3"}}
	else rand 0.143 {delay 0.1 {tex_mod "texset10_var4"}}
	else rand 0.167 {delay 0.1 {tex_mod "texset10_var5"}}
	else rand 0.20 {delay 0.1 {tex_mod "texset10_var6"}}
	else rand 0.25 {delay 0.1 {tex_mod "texset10_var7"}}
	else rand 0.333 {delay 0.1 {tex_mod "texset10_var8"}}
	else rand 0.5 {delay 0.1 {tex_mod "texset10_var9"}}
	}
		
	{if rand 0.091 {delay 0.1 {tex_mod "texset12_var1"}}
	else rand 0.100 {delay 0.1 {tex_mod "texset12_var2"}}
	else rand 0.111 {delay 0.1 {tex_mod "texset12_var3"}}
	else rand 0.125 {delay 0.1 {tex_mod "texset12_var4"}}
	else rand 0.143 {delay 0.1 {tex_mod "texset12_var5"}}
	else rand 0.167 {delay 0.1 {tex_mod "texset12_var6"}}
	else rand 0.200 {delay 0.1 {tex_mod "texset12_var7"}}
	else rand 0.250 {delay 0.1 {tex_mod "texset12_var8"}}
	else rand 0.333 {delay 0.1 {tex_mod "texset12_var9"}}
	else rand 0.500 {delay 0.1 {tex_mod "texset12_var10"}}
	}
		
	{if rand 0.083 {delay 0.1 {tex_mod "texset12_var1"}}
	else rand 0.091 {delay 0.1 {tex_mod "texset12_var2"}}
	else rand 0.100 {delay 0.1 {tex_mod "texset12_var3"}}
	else rand 0.111 {delay 0.1 {tex_mod "texset12_var4"}}
	else rand 0.125 {delay 0.1 {tex_mod "texset12_var5"}}
	else rand 0.143 {delay 0.1 {tex_mod "texset12_var6"}}
	else rand 0.167 {delay 0.1 {tex_mod "texset12_var7"}}
	else rand 0.200 {delay 0.1 {tex_mod "texset12_var8"}}
	else rand 0.250 {delay 0.1 {tex_mod "texset12_var9"}}
	else rand 0.333 {delay 0.1 {tex_mod "texset12_var10"}}
	else rand 0.500 {delay 0.1 {tex_mod "texset12_var11"}}
	}

	{if rand 0.077 {delay 0.1 {tex_mod "texset13_var1"}}
	else rand 0.083 {delay 0.1 {tex_mod "texset13_var2"}}
	else rand 0.091 {delay 0.1 {tex_mod "texset13_var3"}}
	else rand 0.100 {delay 0.1 {tex_mod "texset13_var4"}}
	else rand 0.111 {delay 0.1 {tex_mod "texset13_var5"}}
	else rand 0.125 {delay 0.1 {tex_mod "texset13_var6"}}
	else rand 0.143 {delay 0.1 {tex_mod "texset13_var7"}}
	else rand 0.167 {delay 0.1 {tex_mod "texset13_var8"}}
	else rand 0.200 {delay 0.1 {tex_mod "texset13_var9"}}
	else rand 0.250 {delay 0.1 {tex_mod "texset13_var10"}}
	else rand 0.333 {delay 0.1 {tex_mod "texset13_var11"}}
	else rand 0.500 {delay 0.1 {tex_mod "texset13_var12"}}
	}

		{if rand 0.071 {delay 0.1 {tex_mod "texset14_var1"}}
		else rand 0.077 {delay 0.1 {tex_mod "texset14_var2"}}
		else rand 0.083 {delay 0.1 {tex_mod "texset14_var3"}}
		else rand 0.091 {delay 0.1 {tex_mod "texset14_var4"}}
		else rand 0.100 {delay 0.1 {tex_mod "texset14_var5"}}
		else rand 0.111 {delay 0.1 {tex_mod "texset14_var6"}}
		else rand 0.125 {delay 0.1 {tex_mod "texset14_var7"}}
		else rand 0.143 {delay 0.1 {tex_mod "texset14_var8"}}
		else rand 0.167 {delay 0.1 {tex_mod "texset14_var9"}}
		else rand 0.200 {delay 0.1 {tex_mod "texset14_var10"}}
		else rand 0.250 {delay 0.1 {tex_mod "texset14_var11"}}
		else rand 0.333 {delay 0.1 {tex_mod "texset14_var12"}}
		else rand 0.500 {delay 0.1 {tex_mod "texset14_var13"}}
		}

		{if rand 0.067 {delay 0.1 {tex_mod "texset15_var1"}}
		else rand 0.071 {delay 0.1 {tex_mod "texset15_var2"}}
		else rand 0.077 {delay 0.1 {tex_mod "texset15_var3"}}
		else rand 0.083 {delay 0.1 {tex_mod "texset15_var4"}}
		else rand 0.091 {delay 0.1 {tex_mod "texset15_var5"}}
		else rand 0.100 {delay 0.1 {tex_mod "texset15_var6"}}
		else rand 0.111 {delay 0.1 {tex_mod "texset15_var7"}}
		else rand 0.125 {delay 0.1 {tex_mod "texset15_var8"}}
		else rand 0.143 {delay 0.1 {tex_mod "texset15_var9"}}
		else rand 0.167 {delay 0.1 {tex_mod "texset15_var10"}}
		else rand 0.200 {delay 0.1 {tex_mod "texset15_var11"}}
		else rand 0.250 {delay 0.1 {tex_mod "texset15_var12"}}
		else rand 0.333 {delay 0.1 {tex_mod "texset15_var13"}}
		else rand 0.500 {delay 0.1 {tex_mod "texset15_var14"}}
		}
	{if stuff "helmet"	
		{if rand 0.50 {delay 0.2 {tex_mod "texset_helm2_var1"}}
		{tags add "tex_set"}
		}

		{if rand 0.333 {delay 0.2 {tex_mod "texset_helm3_var1"}}
		else rand 0.5 {delay 0.2 {tex_mod "texset_helm3_var2"}}
		{tags add "tex_set"}
		}

		{if rand 0.25 {delay 0.2 {tex_mod "texset_helm4_var1"}}
		else rand 0.333 {delay 0.2 {tex_mod "texset_helm4_var2"}}
		else rand 0.5 {delay 0.2 {tex_mod "texset_helm4_var3"}}
		{tags add "tex_set"}
		}

		{if rand 0.20 {delay 0.2 {tex_mod "texset_helm5_var1"}}
		else rand 0.25 {delay 0.2 {tex_mod "texset_helm5_var2"}}
		else rand 0.333 {delay 0.2 {tex_mod "texset_helm5_var3"}}
		else rand 0.5 {delay 0.2 {tex_mod "texset_helm5_var4"}}
		{tags add "tex_set"}
		}

		{if rand 0.167 {delay 0.2 {tex_mod "texset_helm6_var1"}}
		else rand 0.20 {delay 0.2 {tex_mod "texset_helm6_var2"}}
		else rand 0.25 {delay 0.2 {tex_mod "texset_helm6_var3"}}
		else rand 0.333 {delay 0.2 {tex_mod "texset_helm6_var4"}}
		else rand 0.50 {delay 0.2 {tex_mod "texset_helm6_var5"}}
		{tags add "tex_set"}
	}

	{if rand 0.143 {delay 0.2 {tex_mod "texset_helm7_var1"}}
	else rand 0.167 {delay 0.2 {tex_mod "texset_helm7_var2"}}
	else rand 0.20 {delay 0.2 {tex_mod "texset_helm7_var3"}}
	else rand 0.25 {delay 0.2 {tex_mod "texset_helm7_var4"}}
	else rand 0.333 {delay 0.2 {tex_mod "texset_helm7_var5"}}
	else rand 0.50 {delay 0.2 {tex_mod "texset_helm7_var6"}}
		{tags add "tex_set"}
	}

	{if rand 0.125 {delay 0.2 {tex_mod "texset_helm8_var1"}}
	else rand 0.143 {delay 0.2 {tex_mod "texset_helm8_var2"}}
	else rand 0.167 {delay 0.2 {tex_mod "texset_helm8_var3"}}
	else rand 0.20 {delay 0.2 {tex_mod "texset_helm8_var4"}}
	else rand 0.25 {delay 0.2 {tex_mod "texset_helm8_var5"}}
	else rand 0.333 {delay 0.2 {tex_mod "texset_helm8_var6"}}
	else rand 0.5 {delay 0.2 {tex_mod "texset_helm8_var7"}}
		{tags add "tex_set"}
	}

	{if rand 0.11 {delay 0.2 {tex_mod "texset_helm9_var1"}}
	else rand 0.125 {delay 0.2 {tex_mod "texset_helm9_var2"}}
	else rand 0.143 {delay 0.2 {tex_mod "texset_helm9_var3"}}
	else rand 0.167 {delay 0.2 {tex_mod "texset_helm9_var4"}}
	else rand 0.20 {delay 0.2 {tex_mod "texset_helm9_var5"}}
	else rand 0.25 {delay 0.2 {tex_mod "texset_helm9_var6"}}
	else rand 0.333 {delay 0.2 {tex_mod "texset_helm9_var7"}}
	else rand 0.5 {delay 0.2 {tex_mod "texset_helm9_var8"}}
		{tags add "tex_set"}
	}

	{if rand 0.1 {delay 0.2 {tex_mod "texset_helm10_var1"}}
	else rand 0.11 {delay 0.2 {tex_mod "texset_helm10_var2"}}
	else rand 0.125 {delay 0.2 {tex_mod "texset_helm10_var3"}}
	else rand 0.143 {delay 0.2 {tex_mod "texset_helm10_var4"}}
	else rand 0.167 {delay 0.2 {tex_mod "texset_helm10_var5"}}
	else rand 0.20 {delay 0.2 {tex_mod "texset_helm10_var6"}}
	else rand 0.25 {delay 0.2 {tex_mod "texset_helm10_var7"}}
	else rand 0.333 {delay 0.2 {tex_mod "texset_helm10_var8"}}
	else rand 0.5 {delay 0.2 {tex_mod "texset_helm10_var9"}}
		{tags add "tex_set"}
	}
		
		{if rand 0.091 {delay 0.2 {tex_mod "texset_helm12_var1"}}
		else rand 0.100 {delay 0.2 {tex_mod "texset_helm12_var2"}}
		else rand 0.111 {delay 0.2 {tex_mod "texset_helm12_var3"}}
		else rand 0.125 {delay 0.2 {tex_mod "texset_helm12_var4"}}
		else rand 0.143 {delay 0.2 {tex_mod "texset_helm12_var5"}}
		else rand 0.167 {delay 0.2 {tex_mod "texset_helm12_var6"}}
		else rand 0.200 {delay 0.2 {tex_mod "texset_helm12_var7"}}
		else rand 0.250 {delay 0.2 {tex_mod "texset_helm12_var8"}}
		else rand 0.333 {delay 0.2 {tex_mod "texset_helm12_var9"}}
		else rand 0.500 {delay 0.2 {tex_mod "texset_helm12_var10"}}
		{tags add "tex_set"}
		}
		
		{if rand 0.083 {delay 0.2 {tex_mod "texset_helm12_var1"}}
		else rand 0.091 {delay 0.2 {tex_mod "texset_helm12_var2"}}
		else rand 0.100 {delay 0.2 {tex_mod "texset_helm12_var3"}}
		else rand 0.111 {delay 0.2 {tex_mod "texset_helm12_var4"}}
		else rand 0.125 {delay 0.2 {tex_mod "texset_helm12_var5"}}
		else rand 0.143 {delay 0.2 {tex_mod "texset_helm12_var6"}}
		else rand 0.167 {delay 0.2 {tex_mod "texset_helm12_var7"}}
		else rand 0.200 {delay 0.2 {tex_mod "texset_helm12_var8"}}
		else rand 0.250 {delay 0.2 {tex_mod "texset_helm12_var9"}}
		else rand 0.333 {delay 0.2 {tex_mod "texset_helm12_var10"}}
		else rand 0.500 {delay 0.2 {tex_mod "texset_helm12_var11"}}
		}

		{if rand 0.077 {delay 0.2 {tex_mod "texset_helm13_var1"}}
		else rand 0.083 {delay 0.2 {tex_mod "texset_helm13_var2"}}
		else rand 0.091 {delay 0.2 {tex_mod "texset_helm13_var3"}}
		else rand 0.100 {delay 0.2 {tex_mod "texset_helm13_var4"}}
		else rand 0.111 {delay 0.2 {tex_mod "texset_helm13_var5"}}
		else rand 0.125 {delay 0.2 {tex_mod "texset_helm13_var6"}}
		else rand 0.143 {delay 0.2 {tex_mod "texset_helm13_var7"}}
		else rand 0.167 {delay 0.2 {tex_mod "texset_helm13_var8"}}
		else rand 0.200 {delay 0.2 {tex_mod "texset_helm13_var9"}}
		else rand 0.250 {delay 0.2 {tex_mod "texset_helm13_var10"}}
		else rand 0.333 {delay 0.2 {tex_mod "texset_helm13_var11"}}
		else rand 0.500 {delay 0.2 {tex_mod "texset_helm13_var12"}}
		}

		{if rand 0.071 {delay 0.2 {tex_mod "texset_helm14_var1"}}
		else rand 0.077 {delay 0.2 {tex_mod "texset_helm14_var2"}}
		else rand 0.083 {delay 0.2 {tex_mod "texset_helm14_var3"}}
		else rand 0.091 {delay 0.2 {tex_mod "texset_helm14_var4"}}
		else rand 0.100 {delay 0.2 {tex_mod "texset_helm14_var5"}}
		else rand 0.111 {delay 0.2 {tex_mod "texset_helm14_var6"}}
		else rand 0.125 {delay 0.2 {tex_mod "texset_helm14_var7"}}
		else rand 0.143 {delay 0.2 {tex_mod "texset_helm14_var8"}}
		else rand 0.167 {delay 0.2 {tex_mod "texset_helm14_var9"}}
		else rand 0.200 {delay 0.2 {tex_mod "texset_helm14_var10"}}
		else rand 0.250 {delay 0.2 {tex_mod "texset_helm14_var11"}}
		else rand 0.333 {delay 0.2 {tex_mod "texset_helm14_var12"}}
		else rand 0.500 {delay 0.2 {tex_mod "texset_helm14_var13"}}
		}

		{if rand 0.067 {delay 0.2 {tex_mod "texset_helm15_var1"}}
		else rand 0.071 {delay 0.2 {tex_mod "texset_helm15_var2"}}
		else rand 0.077 {delay 0.2 {tex_mod "texset_helm15_var3"}}
		else rand 0.083 {delay 0.2 {tex_mod "texset_helm15_var4"}}
		else rand 0.091 {delay 0.2 {tex_mod "texset_helm15_var5"}}
		else rand 0.100 {delay 0.2 {tex_mod "texset_helm15_var6"}}
		else rand 0.111 {delay 0.2 {tex_mod "texset_helm15_var7"}}
		else rand 0.125 {delay 0.2 {tex_mod "texset_helm15_var8"}}
		else rand 0.143 {delay 0.2 {tex_mod "texset_helm15_var9"}}
		else rand 0.167 {delay 0.2 {tex_mod "texset_helm15_var10"}}
		else rand 0.200 {delay 0.2 {tex_mod "texset_helm15_var11"}}
		else rand 0.250 {delay 0.2 {tex_mod "texset_helm15_var12"}}
		else rand 0.333 {delay 0.2 {tex_mod "texset_helm15_var13"}}
		else rand 0.500 {delay 0.2 {tex_mod "texset_helm15_var14"}}
		}
	}
}