(define "sonic_crack"
	{start_sound "hit/Crack/close/" use_position}
	{start_sound "hit/Crack/mid/" use_position}
)
(define "sonic_crack_medium"
	{start_sound "hit/Crack/close/" use_position}
	{start_sound "hit/Crack_med/mid/" use_position}
)
(define "explosion_he_auto"
	{start_sound "detonation/explosion_auto/close/" use_position}
	{start_sound "detonation/explosion_auto/mid/" use_position}
	{start_sound "detonation/explosion_auto/far/" use_position}
)
(define "explosion_ap"
	{start_sound "detonation/explosion_AP/close/" use_position}
	{start_sound "detonation/explosion_AP/mid/" use_position}
	{start_sound "detonation/explosion_AP/far/" use_position}
)
;(define "explosion_ap_large"
	;{start_sound "detonation/explosion_AP/close/" use_position}
	;{start_sound "detonation/explosion_AP/mid/" use_position}
	;{start_sound "detonation/explosion_AP/far/" use_position}
;)
(define "explosion_minimum"
	{start_sound "detonation/explosion_minimum/close/" use_position}
	{start_sound "detonation/explosion_minimum/mid/" use_position}
	{start_sound "detonation/explosion_minimum/far/" use_position}
	{start_sound "detonation/explosion_mechanical/shockwave/short/" use_position}
	{start_sound "detonation/explosion_mechanical/trickle/short/" use_position}
)
(define "explosion_grenade"
	{start_sound "detonation/explosion_grenade/close/" use_position}
	{start_sound "detonation/explosion_grenade/mid/" use_position}
	{start_sound "detonation/explosion_grenade/far/" use_position}
	{start_sound "detonation/explosion_mechanical/shockwave/short/" use_position}
	{start_sound "detonation/explosion_mechanical/trickle/short/" use_position}
)
(define "explosion_small"
	{start_sound "detonation/explosion_small/close/" use_position}
	{start_sound "detonation/explosion_small/mid/" use_position}
	{start_sound "detonation/explosion_small/far/" use_position}
	{start_sound "detonation/explosion_mechanical/shockwave/medium/" use_position}
	{start_sound "detonation/explosion_mechanical/trickle/short/" use_position}
)
(define "explosion_medium"
	{start_sound "detonation/explosion_medium/close/" use_position}
	{start_sound "detonation/explosion_medium/mid/" use_position}
	{start_sound "detonation/explosion_medium/far/" use_position}
	{start_sound "detonation/explosion_mechanical/shockwave/medium/" use_position}
	{start_sound "detonation/explosion_mechanical/trickle/long/" use_position}
)
(define "explosion_large"
  	{start_sound "detonation/explosion_large/close/" use_position}
  	{start_sound "detonation/explosion_large/mid/" use_position}
	{start_sound "detonation/explosion_large/far/" use_position}
	{start_sound "detonation/explosion_mechanical/shockwave/medium/" use_position}
	{start_sound "detonation/explosion_mechanical/trickle/long/" use_position}
)
(define "explosion_massive"
 	{start_sound "detonation/explosion_massive/close/" use_position}
 	{start_sound "detonation/explosion_massive/mid/" use_position}
	{start_sound "detonation/explosion_massive/far/" use_position}
	{start_sound "detonation/explosion_mechanical/shockwave/long/" use_position}
	{start_sound "detonation/explosion_mechanical/trickle/long/" use_position}
)
(define "explosion_HEAT"
 	{start_sound "detonation/explosion_HEAT/close/" use_position}
 	{start_sound "detonation/explosion_HEAT/mid/" use_position}
	{start_sound "detonation/explosion_HEAT/far/" use_position}
	{start_sound "detonation/explosion_mechanical/shockwave/short/" use_position}
	{start_sound "detonation/explosion_mechanical/trickle/short/" use_position}
)
(define "explosion_HEAT_large"
 	{start_sound "detonation/explosion_HEAT_large/close/" use_position}
  	{start_sound "detonation/explosion_HEAT_large/mid/" use_position}
	{start_sound "detonation/explosion_HEAT_large/far/" use_position}
	{start_sound "detonation/explosion_mechanical/shockwave/medium/" use_position}
	{start_sound "detonation/explosion_mechanical/trickle/long/" use_position}
)
